site_name: Kyronode Services
site_url: https://services.kyronode.xyz

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    previous: fontawesome/solid/arrow-left
    next: fontawesome/solid/arrow-right
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight

  palette:
    # Automatic: adapt to user's OS preference
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  homepage: https://kyronode.xyz
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kyronode
    - icon: fontawesome/brands/twitter
      link: https://x.com/kyronode
    - icon: fontawesome/brands/telegram
      link: https://t.me/kyronode
    - icon: fontawesome/solid/paper-plane
      link: mailto:kyronodes@gmail.com

nav:
  - Home: index.md
  - Mainnet:
      - Overview: mainnet/_index.md
      - Bitbadges:
          - Network: mainnet/Bitbadges/network.md
          - Installation: mainnet/Bitbadges/installation.md
          - Cheat Sheet: mainnet/Bitbadges/cheatsheet.md
          - Upgrade: mainnet/Bitbadges/upgrade.md
      - Zenrock:
          - Network: mainnet/Zenrock/network.md
          - Installation: mainnet/Zenrock/installation.md
          - Cheat Sheet: mainnet/Zenrock/cheatsheet.md
          - Upgrade: mainnet/Zenrock/upgrade.md
      - Paxi:
          - Installation: mainnet/Paxi/installation.md
          - Cheat Sheet: mainnet/Paxi/cheatsheet.md
          - Upgrade: mainnet/Paxi/upgrade.md
  - Testnet:
      - Overview: testnet/_index.md
      - Empeiria:
          - Network: testnet/Empeiria/network.md
          - Installation: testnet/Empeiria/installation.md
          - Cheat Sheet: testnet/Empeiria/cheatsheet.md
          - Upgrade: testnet/Empeiria/upgrade.md
      - Kiichain:
          - Network: testnet/Kiichain/network.md
          - Installation: testnet/Kiichain/installation.md
          - Cheat Sheet: testnet/Kiichain/cheatsheet.md
          - Upgrade: testnet/Kiichain/upgrade.md
      - Lumera:
          - Network: testnet/Lumera/network.md
          - Installation: testnet/Lumera/installation.md
          - Cheat Sheet: testnet/Lumera/cheatsheet.md
          - Upgrade: testnet/Lumera/upgrade.md
      - Safrochain:
          - Network: testnet/Safrochain/network.md
          - Installation: testnet/Safrochain/installation.md
          - Cheat Sheet: testnet/Safrochain/cheatsheet.md
          - Upgrade: testnet/Safrochain/upgrade.md
      - Zenrock:
          - Network: testnet/Zenrock/network.md
          - Installation: testnet/Zenrock/installation.md
          - Cheat Sheet: testnet/Zenrock/cheatsheet.md
          - Upgrade: testnet/Zenrock/upgrade.md

copyright: Copyright &copy; 2025 KyroNode. All rights reserved.
