site_name: Kyronode Services
site_url: https://services.kyronode.xyz

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    previous: fontawesome/solid/arrow-left
    next: fontawesome/solid/arrow-right
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight

  palette:
    # Automatic: adapt to user's OS preference
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  homepage: https://kyronode.xyz
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kyronode
    - icon: fontawesome/brands/twitter
      link: https://x.com/kyronode
    - icon: fontawesome/brands/telegram
      link: https://t.me/kyronode
    - icon: fontawesome/solid/paper-plane
      link: mailto:kyronodes@gmail.com

nav:
  - Home: index.md
  - About KyroNode: about.md
  - Mainnet:
      - Overview: mainnet/_index.md
      - Chain1:
          - Installation: mainnet/chain1/installation.md
          - Cheat Sheet: mainnet/chain1/cheatsheet.md
          - Upgrade: mainnet/chain1/upgrade.md
  - Testnet:
      - Overview: testnet/_index.md
      - Kiichain:
          - Installation: testnet/Kiichain/installation.md
          - Cheat Sheet: testnet/Kiichain/cheatsheet.md
          - Upgrade: testnet/Kiichain/upgrade.md
          
extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2022-2025 KyroNode. All rights reserved.