name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main  # trigger setiap push ke main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs==1.* mkdocs-material==9.6.18

      - name: Check versions
        run: |
          echo "=== MkDocs & MkDocs-Material Versions ==="
          mkdocs --version
          pip show mkdocs-material

      - name: Build MkDocs (verbose)
        run: mkdocs build --verbose

      - name: Debug build output
        run: |
          echo "=== site files ==="
          ls -R site || true
          echo "=== check data-md-color-scheme ==="
          grep -R "data-md-color-scheme" site || true
          echo "=== check toggle icons ==="
          grep -R "brightness-auto\|brightness-7\|brightness-4" site || true

      - name: Add CNAME for custom domain
        run: echo "services.kyronode.xyz" > ./site/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
